docs(microservices): add instruction to use transport in MessagePattern
nestjs/docs.nestjs.com pull request #1246
Opened 2020-05-16 13:39 UTC by barbarosh

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number:  https://github.com/nestjs/nest/issues/4769

## What is the new behavior?
Add code example and instruction how to use transport in MessagePattern decorator

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2020-05-23 10:53 UTC, kamilmysliwiec commented
Thanks for the PR! I believe that we should rather add it to the Hybrid Applications chapter instead. Adding more content to the "Basics" section that is irrelevant to many developers might just make this chapter unnecessarily complicated. Do you have any thoughts here @johnbiundo?

2020-05-26 19:53 UTC, johnbiundo commented
I agree with @kamilmysliwiec's comment about moving to the hybrid chapter.

2020-05-27 10:42 UTC, barbarosh commented
@kamilmysliwiec @johnbiundo Ok I will move

2020-07-09 09:01 UTC, kamilmysliwiec commented
@barbarosh do you have some time to look into this by chance? 🏓

2020-07-10 09:58 UTC, barbarosh commented
> @barbarosh do you have some time to look into this by chance? 🏓  

Yes I will do it on this weekend

2020-07-14 12:02 UTC, barbarosh commented
> @barbarosh do you have some time to look into this by chance? 🏓

on this week I will do it 😅

2020-08-10 14:38 UTC, barbarosh commented
@kamilmysliwiec Updated PR

2020-11-05 13:52 UTC, kamilmysliwiec commented
Would you be able to review this PR @jmcdo29? :) (grammar-wise etc) Apologies for pinging you in so many places! Trying to clean up some of the remaining, opened PRs

2020-11-05 16:18 UTC, jmcdo29 requested changes
Made some small grammar related comments

2020-11-05 16:18 UTC, jmcdo29 commented on content/faq/hybrid-application.md
> +For bind `@MessagePattern()` only to one transport of microservices in hybrid application with multiple microservices can use second argument which should get value from `Transport` enum
For bind...

To

To bind...

2020-11-05 16:18 UTC, jmcdo29 commented on content/faq/hybrid-application.md
> +For bind `@MessagePattern()` only to one transport of microservices in hybrid application with multiple microservices can use second argument which should get value from `Transport` enum
`with multiple microservices can use`

To

`with multiple microservices we can use`

2020-11-05 16:18 UTC, jmcdo29 commented on content/faq/hybrid-application.md
> +For bind `@MessagePattern()` only to one transport of microservices in hybrid application with multiple microservices can use second argument which should get value from `Transport` enum
`can use second argument`

To

`can use the second argument`

2020-11-05 16:18 UTC, jmcdo29 commented on content/faq/hybrid-application.md
> +For bind `@MessagePattern()` only to one transport of microservices in hybrid application with multiple microservices can use second argument which should get value from `Transport` enum
`only to one`

To

`to only one`

2020-11-06 08:05 UTC, kamilmysliwiec commented on content/faq/hybrid-application.md
> +For bind `@MessagePattern()` only to one transport of microservices in hybrid application with multiple microservices can use second argument which should get value from `Transport` enum
```suggestion
To bind `@MessagePattern()` to only one transport strategy (for example, MQTT) in a hybrid application with multiple microservices, we can pass the second argument of type `Transport` which is an enum with all the built-in transport strategies defined.
```

2020-11-06 08:06 UTC, kamilmysliwiec commented
Thanks!

2020-11-06 08:06 UTC, merged