docs(graphql): added docs for graphql model shim
nestjs/docs.nestjs.com pull request #1505
Opened 2020-10-08 16:21 UTC by maayanbar13

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Docs
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Added another doc page in the `graphql` section to document how to share `Code-first` `graphql` models with your front-end application.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Documents the model shim feature from [nestjs/graphql#1184](https://github.com/nestjs/graphql/pull/1184).

2020-12-08 10:52 UTC, johannesschobel commented on content/graphql/sharing-models.md
> +but there's a problem: the models created using the Code first approach are heavily decorated with graphql related decorators. Those decorators are irrelevant in the frontend, negatively impacting pe
```suggestion
But there's a problem: the models created using the code first approach are heavily decorated with graphql related decorators. Those decorators are irrelevant in the frontend, negatively impacting performance.

```

2020-12-08 10:52 UTC, johannesschobel commented on content/graphql/sharing-models.md
> +To solve this issue, nest provides a "shim" which allows you to replace the original decorators with inert code by using a `webpack` (or similar) configuration.
```suggestion
To solve this issue, nestjs provides a "shim" which allows you to replace the original decorators with inert code by using a `webpack` (or similar) configuration.    

```

2020-12-15 16:43 UTC, jmcdo29 requested changes
Nice addition! I added a few comments.

2020-12-15 16:43 UTC, jmcdo29 commented on content/graphql/sharing-models.md
> +To solve this issue, nest provides a "shim" which allows you to replace the original decorators with inert code by using a `webpack` (or similar) configuration.
I'd say just capitalize "Nest" here. 

```suggestion
To solve this issue, Nest provides a "shim" which allows you to replace the original decorators with inert code by using a `webpack` (or similar) configuration. 
```

2020-12-15 16:43 UTC, jmcdo29 commented on content/graphql/sharing-models.md
> +but there's a problem: the models created using the Code first approach are heavily decorated with graphql related decorators. Those decorators are irrelevant in the frontend, negatively impacting pe
```suggestion
But there's a problem: the models created using the code first approach are heavily decorated with GraphQL related decorators. Those decorators are irrelevant in the frontend, negatively impacting performance.
```
```

2020-12-15 17:20 UTC, jmcdo29 approved these changes

2021-02-05 17:21 UTC, maayanbar13 commented
Any reason this is still blocked?

2022-01-31 03:05 UTC, micalevisk approved these changes

2022-03-20 11:00 UTC, Tony133 approved these changes

2023-02-06 08:07 UTC, kamilmysliwiec commented on content/graphql/sharing-models.md
> +### Sharing Models
```suggestion
### Sharing Models

```

2023-02-06 08:07 UTC, kamilmysliwiec commented on content/graphql/sharing-models.md
> +### Sharing Models
```suggestion
### Sharing models

```

2023-02-06 08:22 UTC, merged