feat(yam-config): adding yaml custom configuration
nestjs/docs.nestjs.com pull request #1561
Opened 2020-11-17 14:43 UTC by iam-dev

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Docs
[ ] Other... Please describe:
```

## What is the current behavior?

Adding doc how to add yaml file custom configuration

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2020-11-17 15:06 UTC, jmcdo29 requested changes

2020-11-17 15:06 UTC, jmcdo29 commented on content/techniques/configuration.md
> +To be able to read yaml file and put the configuration in json object, we need to add "js-yaml" to our project.
```suggestion
To be able to read yaml file and put the configuration in json object, we need to add `js-yaml` to our project.
```

2020-11-17 15:06 UTC, jmcdo29 commented on content/techniques/configuration.md
> +import { registerAs } from '../../lib/utils';
I assume this is meant to be fro m`@nestjs/config`?

2020-11-17 15:06 UTC, jmcdo29 commented on content/techniques/configuration.md
> +      imports: [AppModule.withYamlConfigurations()],
Where does `withYamlConfigurations()` come from?

2020-11-17 15:06 UTC, jmcdo29 commented on content/techniques/configuration.md
> +    const config = app.get(AppModule).getYamlConfig();
Similarly, where does `getYamlConfig()` come from?

2020-11-17 18:10 UTC, iam-dev commented on content/techniques/configuration.md
> +      imports: [AppModule.withYamlConfigurations()],
check commit e87b6b1c323d754acf65cfb1c6624ba24295c116

2020-11-17 18:11 UTC, iam-dev commented on content/techniques/configuration.md
> +    const config = app.get(AppModule).getYamlConfig();
check commit e87b6b1c323d754acf65cfb1c6624ba24295c116

2020-11-17 18:11 UTC, jmcdo29 approved these changes

2020-11-17 18:18 UTC, iam-dev commented
I'm not sure why those checks are failling. I'm only changing configuration.md file

2020-11-18 09:22 UTC, kamilmysliwiec commented
Thanks!

2020-11-18 09:23 UTC, merged