docs(config): add use cache
nestjs/docs.nestjs.com pull request #1571
Opened 2020-11-25 10:36 UTC by Sikora00

refs nestjs/config#121

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Docs
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2020-11-26 18:12 UTC, jmcdo29 commented on content/techniques/configuration.md
> +Accessing `process.env` is slow. To increase the performance of the `ConfigService.get` method for variables stored in the `proccess.env` set the `cache` property of the options object we pass to the
```suggestion
As accessing `process.env` can be slow, you can set the `cache` property of the options object passed to `ConfigModule.forRoot()` to increase the performance of `ConfifService.get` when it comes to variables stored in `process.env`
```

2020-11-26 18:15 UTC, jmcdo29 requested changes
Thanks for the addition. I've added a suggestion that I think reads a little better

2020-11-26 18:49 UTC, Sikora00 commented
Greate @jmcdo29 ! Changes Applied :)

2020-11-26 18:59 UTC, jmcdo29 approved these changes

2020-11-27 09:21 UTC, merged

2020-11-27 09:23 UTC, kamilmysliwiec commented
Thanks @Sikora00!