Add a section for overriding APP_* token providers
nestjs/docs.nestjs.com pull request #1578
Opened 2020-11-30 10:52 UTC by davids-sparkshare

This adds a section on how to replace `APP_*` token providers in testing. This follows the description by @kamilmysliwiec in https://github.com/nestjs/nest/issues/4053 . I've used the solution in my project and it worked great.

Thanks to @jmcdo29 who pointed me to that issue when I was struggling with this.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Docs
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest/issues/5821

## What is the new behavior?

more docs

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2020-12-08 09:52 UTC, johannesschobel commented on content/fundamentals/unit-testing.md
> +Now the `JwtAuthGuard` is visible to nest as a regular provider that can be overridden when creating the test module:
please use `nestjs` instead of `nest`

2020-12-08 09:52 UTC, johannesschobel commented on content/fundamentals/unit-testing.md
> +If you have a [globally registered guard](/security/authentication#enable-authentication-globally) (or pipe, interceptor, or filter), you need to take a few more steps to override that enhancer. To r
`recap` instead of `re-cap`

2020-12-08 09:52 UTC, johannesschobel commented on content/fundamentals/unit-testing.md
> +Now the `JwtAuthGuard` is visible to nest as a regular provider that can be overridden when creating the test module:
`TestingModule` instead of `test module`

2020-12-08 10:46 UTC, johannesschobel commented on content/fundamentals/unit-testing.md
> +If you have a [globally registered guard](/security/authentication#enable-authentication-globally) (or pipe, interceptor, or filter), you need to take a few more steps to override that enhancer. To r
```suggestion
If you have a [globally registered guard](/security/authentication#enable-authentication-globally) (or pipe, interceptor, or filter), you need to take a few more steps to override that enhancer. To recap the original registration looks like this:
```

2020-12-08 10:46 UTC, johannesschobel commented on content/fundamentals/unit-testing.md
> +Now the `JwtAuthGuard` is visible to nest as a regular provider that can be overridden when creating the test module:
```suggestion
Now the `JwtAuthGuard` is visible to nestjs as a regular provider that can be overridden when creating the `TestingModule`:
```

2020-12-12 15:53 UTC, johannesschobel approved these changes

2020-12-14 10:44 UTC, kamilmysliwiec commented
Can you review @jmcdo29 by chance? 🤞

2020-12-14 16:31 UTC, jmcdo29 requested changes

2020-12-14 16:31 UTC, jmcdo29 commented on content/fundamentals/unit-testing.md
> +Now the `JwtAuthGuard` is visible to nestjs as a regular provider that can be overridden when creating the `TestingModule`:
```suggestion
Now the `JwtAuthGuard` is visible to nest as a regular provider that can be overridden when creating the `TestingModule`:
```

There's other places in the docs where the framework is referred to just as `nest` and it reads a bit more easily. I'd prefer to follow that if possible.

2020-12-15 09:08 UTC, kamilmysliwiec commented on content/fundamentals/unit-testing.md
> +#### Overriding globally registered providers
```suggestion
#### Overriding globally registered enhancers
```

2020-12-15 09:09 UTC, kamilmysliwiec commented on content/fundamentals/unit-testing.md
> +This is registering the guard as a "multi"-provider through the `APP_*` token. To be able to replace the JwtAuthGuard here, the registration needs to use an existing provider in this slot:
```suggestion
This is registering the guard as a "multi"-provider through the `APP_*` token. To be able to replace the `JwtAuthGuard` here, the registration needs to use an existing provider in this slot:
```

2020-12-28 10:21 UTC, davids-sparkshare commented
Applied all suggestions from code review.

2020-12-28 16:56 UTC, jmcdo29 approved these changes

2021-01-07 09:35 UTC, kamilmysliwiec commented on content/fundamentals/unit-testing.md
> +Now the `JwtAuthGuard` is visible to nest as a regular provider that can be overridden when creating the `TestingModule`:
```suggestion
Now the `JwtAuthGuard` is visible to Nest as a regular provider that can be overridden when creating the `TestingModule`:
```

2021-01-07 09:49 UTC, kamilmysliwiec commented on content/fundamentals/unit-testing.md
> +If you have a [globally registered guard](/security/authentication#enable-authentication-globally) (or pipe, interceptor, or filter), you need to take a few more steps to override that enhancer. To r
```suggestion
If you have a globally registered guard (or pipe, interceptor, or filter), you need to take a few more steps to override that enhancer. To recap the original registration looks like this:
```

2021-01-07 09:49 UTC, kamilmysliwiec commented
LGTM

2021-01-07 09:49 UTC, merged