[Docs]: Improve Events
nestjs/docs.nestjs.com pull request #1595
Opened 2020-12-10 14:06 UTC by johannesschobel

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Docs
[ ] Other... Please describe:
```

## What is the current behavior?

This PR does the following thing:
- change the order of the sections in the `events` part. Now, first emitting events will be described, then listening to events
- the use of multilevel wildcards are explained. regular wildcards (`*`) are only one level deep!

Issue Number: N/A
https://github.com/nestjs/event-emitter/issues/25

## What is the new behavior?

Clarify the use of events and multilevel wildcards

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2020-12-14 10:40 UTC, kamilmysliwiec commented
@jmcdo29 can you give it a quick review? Thanks @johannesschobel!

2020-12-14 16:36 UTC, jmcdo29 requested changes
Overall, looks great. Made a few small comment that aren't necessary, but would be nice to fix up.

2020-12-14 16:36 UTC, jmcdo29 commented on content/techniques/events.md
> +use the `multilevel wildcard` pattern (i.e, `**`), described in the `EventEmitter2` package.
Any chance you can link to `EventEmitter2` documentation (GitHub, docs site, whatever they have)?

2020-12-14 16:36 UTC, jmcdo29 commented on content/techniques/events.md
> +Then use it in a class as follows.
```suggestion
Then use it in a class as follows:
```

2020-12-14 18:58 UTC, johannesschobel commented
@jmcdo29 : applied your minor change-requests
@kamilmysliwiec : all done, ready to merge

2020-12-14 19:06 UTC, jmcdo29 approved these changes
LGTM

2020-12-15 09:12 UTC, kamilmysliwiec commented on content/techniques/events.md
> +  console.log('listener triggered');
```suggestion
  // handle and process an event
```

2020-12-15 09:13 UTC, merged

2020-12-15 09:13 UTC, kamilmysliwiec commented
Thanks!