docs(typeorm): added hint for method getConnectionOptions
nestjs/docs.nestjs.com pull request #1782
Opened 2021-02-18 21:08 UTC by Tony133

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] Docs
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1591 

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, added hint for method getConnectionOptions

2021-02-19 07:34 UTC, kamilmysliwiec commented
Thanks Tony!

Can you review grammar/style-wise etc @jmcdo29 🙌 ?

2021-02-19 17:10 UTC, jmcdo29 requested changes

2021-02-19 17:10 UTC, jmcdo29 commented on content/techniques/sql.md
> +> info **Hint** Sometimes, you may want to use multiple configurations using different formats and read connection options from ormconfig file (or ENV variables) for these cases you can use `getConne
```suggestion
> info **Hint** Sometimes, you may want to use multiple configurations using different formats and read connection options from an ormconfig file (or ENV variables). For these cases you can use the `getConnectionOptions()` method. For other more information [you can view TypeORM's docs](https://typeorm.io/#/using-ormconfig/overriding-options-defined-in-ormconfig).
```

2021-02-19 17:25 UTC, jmcdo29 approved these changes

2021-02-25 12:59 UTC, kamilmysliwiec commented
Since the proposed hint was somewhat confusing and added in the wrong place, I've just manually pushed a change in this commit https://github.com/nestjs/docs.nestjs.com/commit/53a15ac5ab897f29cb161632dfcd60300a0bf943. Thanks for your contribution anyway!

2021-02-25 12:59 UTC, closed without merging