feat(microservice): add TLS over TCP support
nestjs/docs.nestjs.com pull request #1961
Opened 2021-07-12 10:47 UTC by Flusinerd

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Docs
- [ ] Other... Please describe:

## What is the current behavior?

No docs for TLS over TCP support.

Issue Number: [6745](https://github.com/nestjs/nest/issues/6745)
Pull Request: [7516](https://github.com/nestjs/nest/pull/7516)

## What is the new behavior?
Added ``TLS support`` section to ``Basics`` page in ``Microservice`` section.

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2022-01-13 23:00 UTC, elucidsoft commented
Is this going to get committed?

2022-01-14 09:08 UTC, Flusinerd commented
@elucidsoft it's still wip. I don't have time atm to work on this. Check #7516

2022-03-17 12:04 UTC, Tony133 requested changes

2022-03-17 12:04 UTC, Tony133 commented on content/microservices/basics.md
> +The client uses the `TLSSocket()` constructor.
```suggestion
For further information refer to Nodes [TLS](https://nodejs.org/api/tls.html) module:  
- The server uses the `createServer(options)` method.  
- The client uses the `TLSSocket()` constructor.
```

2022-03-17 12:04 UTC, Tony133 commented on content/microservices/basics.md
> +
```suggestion
```

2022-03-17 12:08 UTC, Tony133 commented
I've just pointed out a few small things to change, but otherwise it looks like a good addition to the documentation. 👍

2024-10-18 11:52 UTC, merged