Add required modifications to app.module.ts
nestjs/docs.nestjs.com pull request #2084
Opened 2021-10-23 16:27 UTC by rinogo

Please feel free to tweak this as appropriate. This is a great step-by-step tutorial, but it leaves out this necessary step. Not a big deal for a NestJS expert, but a newbie (like myself) might get tripped up.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2022-03-20 20:51 UTC, johannesschobel requested changes
however, i am not sure, if these changes are really needed..

2022-03-20 20:51 UTC, johannesschobel commented on content/recipes/prisma.md
> +First, specify the new Prisma services in your: `app.module.ts`:
```suggestion
First, add the newly generated Prisma services to your `app.module.ts`:
```

2022-03-20 20:51 UTC, johannesschobel commented on content/recipes/prisma.md
> +...
```suggestion
export class ... { }
```

2022-04-07 13:21 UTC, kamilmysliwiec commented
Yeah, I agree with @johannesschobel. These changes seem to be very trivial. I'd not recommend following tutorials from the "Recipes" section before going through all pages from the "Overview".

Thanks for your contribution anyways!

2022-04-07 13:21 UTC, closed without merging

2022-04-07 15:07 UTC, rinogo commented
Yes, it is a minor change, but I do think it improves the docs. Prior to running into trouble, I read the entire "Overview" as well as most of the other sections as well. However, just reading the docs doesn't mean that they're instantly and fully internalized.

I think trivial changes like this can help new users get up to speed in NestJS with less friction. Ultimately, reducing friction improves adoption - isn't that a worthy goal?