docs: add info about docker integration
nestjs/docs.nestjs.com pull request #2120
Opened 2021-11-26 12:42 UTC by davideicardi

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X ] Docs
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?
- [ ] Yes
- [X ] No

2021-12-30 23:28 UTC, micalevisk commented
what about add a link to this basic repo github template: https://github.com/jmcdo29/nest-docker-template

2022-03-20 20:57 UTC, johannesschobel requested changes

2022-03-20 20:57 UTC, johannesschobel commented on content/fundamentals/container-integration.md
> +Here a `Dockerfile` template that you can use:
```suggestion
Here is a `Dockerfile` template that can be used as a template:
```

2022-03-20 21:37 UTC, micalevisk commented
I guess this won't get merged due to this: https://github.com/nestjs/nest/pull/5810#issuecomment-740515157

2022-03-21 07:03 UTC, johannesschobel commented
> I guess this won't get merged due to this: https://github.com/nestjs/nest/pull/5810#issuecomment-740515157 

Dear @micalevisk , I still think this may be a valuable contribution to the docs to give an idea how to start.. maybe @davideicardi can better highlight that dockerizing an app is highly subjective and depend on various factors (i.e., runtime environment, node engine, ...) and that the snippets provided is just a basic idea..

2022-03-21 07:43 UTC, kamilmysliwiec commented
https://github.com/nestjs/nest/pull/5810#issuecomment-740515157

2022-03-21 07:43 UTC, closed without merging