add ApiPropertyOptional
nestjs/docs.nestjs.com pull request #2183
Opened 2022-01-22 08:58 UTC by tahamansoor

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2022-02-09 00:59 UTC, micalevisk commented on content/openapi/types-and-parameters.md
> +  breed: string;
```suggestion
  breed?: string;
```

2022-02-09 01:01 UTC, micalevisk commented
What if you add a new optional field on the `CreateCatDto` that already exists? It will be easier to follow I guess

2022-02-09 13:56 UTC, tahamansoor commented
> What if you add a new optional field on the `CreateCatDto` that already exists? It will be easier to follow I guess

` name?: string;` 
are you saying like mentioned above? if yes that does not work I have tried this before

2022-02-09 14:02 UTC, micalevisk commented
nvm

I think if you just change the line

![image](https://user-images.githubusercontent.com/13461315/153216551-ec3c765d-a175-4df8-b300-3b23782e9207.png)

to

```
As you can see, the definition is empty although the class has a few declared properties.
In order to make the class properties visible to the `SwaggerModule`, we have to either annotate them with the `@ApiProperty()` decorator (or `@ApiOptionalProperty()` for optional fields) or use the CLI plugin (read more in the Plugin section) which will do it automatically:
```

would be enough

2022-02-10 11:43 UTC, tahamansoor commented
> nvm
> 
> I think if you just change the line
> 
> ![image](https://user-images.githubusercontent.com/13461315/153216551-ec3c765d-a175-4df8-b300-3b23782e9207.png)
> 
> to
> 
> ```
> As you can see, the definition is empty although the class has a few declared properties.
> In order to make the class properties visible to the `SwaggerModule`, we have to either annotate them with the `@ApiProperty()` decorator (or `@ApiOptionalProperty()` for optional fields) or use the CLI plugin (read more in the Plugin section) which will do it automatically:
> ```
> 
> would be enough

yes that's a good point

2022-03-20 20:26 UTC, johannesschobel requested changes

2022-03-20 20:26 UTC, johannesschobel commented on content/openapi/types-and-parameters.md
> +  breed: string;
i guess we should use the `?` here?!

```suggestion
  breed?: string;
```

2022-04-07 12:19 UTC, kamilmysliwiec commented
We decided not to mention `@ApiPropertyOptional` and encourage developers to use `@ApiProperty({ required: false })` instead

2022-04-07 12:19 UTC, closed without merging

2022-04-07 12:43 UTC, tahamansoor commented on content/openapi/types-and-parameters.md
> +  breed: string;
I have tried it 
It doesn't work