docs(microservices): add commit offsets doc for kafka
nestjs/docs.nestjs.com pull request #2230
Opened 2022-02-28 19:31 UTC by davidschuette

This is the associated documentation for PR #9270 of nest.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [PR #9270 of nestjs/nest](https://github.com/nestjs/nest/pull/9270)

## What is the new behavior?
Add documentation for usage of `commitOffsets` for ClientKafka.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-03-20 20:14 UTC, johannesschobel requested changes

2022-03-20 20:14 UTC, johannesschobel commented on content/microservices/kafka.md
> +Comitting offsets is essential when working with kafka. Per default messages will be automatically committed after a specific time. For more information visit [kafkajs docs](https://kafka.js.org/docs
```suggestion
Committing offsets is essential when working with Kafka. Per default, messages will be automatically committed after a specific time. For more information visit [KafkaJS docs](https://kafka.js.org/docs/consuming#autocommit). `ClientKafka` offers a way to manually commit offsets that work like the [native KafkaJS implementation](https://kafka.js.org/docs/consuming#manual-committing).
```

2022-03-20 20:14 UTC, johannesschobel commented on content/microservices/kafka.md
> +@EventPattern('user_created')
Is using `_` (underscore) a good idea? Because it is rarely used in the TypeScript world, i guess..

2022-03-28 20:28 UTC, davidschuette commented
@johannesschobel Thank you for the review. I will update the PR with your suggestions and with some more content when this [PR](https://github.com/nestjs/nest/pull/9293) gets merged.

2023-02-06 08:36 UTC, kamilmysliwiec commented on content/microservices/kafka.md
> +To disable auto-committing of messages set `autoCommit: false` in the `run` config.
```suggestion
To disable auto-committing of messages set `autoCommit: false` in the `run` configuration, as follows:
```

2023-02-06 08:43 UTC, kamilmysliwiec commented on content/microservices/kafka.md
> +}
```suggestion
@EventPattern('user.created')
async handleUserCreated(@Payload() data: IncomingMessage, @Ctx() context: KafkaContext) {
  // business logic
  
  const originalMessage = context.getMessage();
  const { topic, partition, offset } = originalMessage;
  await this.client.commitOffsets([{ topic, partition, offset }])
}
```

2023-02-06 08:44 UTC, kamilmysliwiec commented on content/microservices/kafka.md
> +}
```suggestion
@Bind(Payload(), Ctx())
@EventPattern('user.created')
async handleUserCreated(data, context) {
  // business logic

  const originalMessage = context.getMessage();
  const { topic, partition, offset } = originalMessage;
  await this.client.commitOffsets([{ topic, partition, offset }])
}
```

2023-02-06 08:47 UTC, merged