docs(microservices): add docs about binding patterns for custom transporter
nestjs/docs.nestjs.com pull request #2247
Opened 2022-03-17 02:19 UTC by xavierchow

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest/issues/9341

## What is the new behavior?
A self-defined Symbol from a custom transporter can be set for EventPattern & MessagePattern decorator to avoid binding patterns to wrong microservices in multiple microservices circumstances.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-03-17 11:59 UTC, Tony133 requested changes

2022-03-17 11:59 UTC, Tony133 commented on content/faq/hybrid-application.md
> +To bind `@MessagePattern()` to only one transport strategy (for example, MQTT) in a hybrid application with multiple microservices, we can pass the second argument with either of below,
```suggestion
To bind `@MessagePattern()` to only one transport strategy (for example, MQTT) in a hybrid application with multiple microservices, we can pass the second argument with either of below:
```

2022-03-17 12:31 UTC, Tony133 approved these changes

2024-09-04 09:51 UTC, nllahat commented
Hey, any reason this pr haven't been merged yet?

2026-08-28 09:54 UTC, merged