docs: how to build or import a custom scalar
nestjs/docs.nestjs.com pull request #2293
Opened 2022-04-25 04:27 UTC by jfairley

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Adding documentation on how to register a custom scalar. This is different from the existing documentation that merely describes how to _override_ a built-in scalar. Fwiw, some of this is covered already in the "schema-first" section, but being there, I did not realize how relevant it was until I spent a lot of time doing outside research and troubleshooting. This adds more clarity for those choosing the "code-first" approach.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-04-25 15:17 UTC, jmcdo29 requested changes
Great addition! I've added on suggested change, but otherwise this looks good to me

2022-04-25 15:17 UTC, jmcdo29 commented on content/graphql/scalars.md
> +}
```suggestion
function validate(uuid: unknown): string | never {
  if (typeof uuid !== "string" || !regex.test(uuid)) {
    throw new Error("invalid uuid");
  }
  return uuid;
}
```

2022-04-27 17:46 UTC, jfairley commented
Thanks @jmcdo29. Suggestion committed.

2022-04-27 17:48 UTC, jmcdo29 approved these changes

2022-04-27 19:41 UTC, Tony133 approved these changes

2022-05-14 16:04 UTC, jfairley commented
@jmcdo29 @Tony133 Is there anything else I need to do to get this merged?

2022-05-14 16:20 UTC, jmcdo29 commented
> @jmcdo29 @Tony133 Is there anything else I need to do to get this merged?

Right now, nope. Just gotta wait for @kamilmysliwiec to merge it

2022-05-20 12:07 UTC, merged

2022-05-20 12:07 UTC, kamilmysliwiec commented
LGTM