docs(techniques): renamed fastify plugins
nestjs/docs.nestjs.com pull request #2296
Opened 2022-05-05 17:07 UTC by Tony133

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Renamed fastify plugins:
- `@fastify-cookie`
- `@fastify-compress`

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-05-05 19:35 UTC, micalevisk requested changes

2022-05-05 19:35 UTC, micalevisk commented on content/techniques/compression.md
> +$ npm i --save @fastify-compress
```suggestion
$ npm i --save @fastify/compress
```

2022-05-05 19:35 UTC, micalevisk commented on content/techniques/compression.md
> +import compression from '@fastify-compress';
```suggestion
import compression from '@fastify/compress';
```

2022-05-05 19:35 UTC, micalevisk commented on content/techniques/compression.md
> +The above tells `@fastify-compress` to only use gzip and deflate encodings, preferring gzip if the client supports both.
```suggestion
The above tells `@fastify/compress` to only use gzip and deflate encodings, preferring gzip if the client supports both.
```

2022-05-05 19:35 UTC, micalevisk commented on content/techniques/cookies.md
> +$ npm i @fastify-cookie
```suggestion
$ npm i @fastify/cookie
```

2022-05-05 19:35 UTC, micalevisk commented on content/techniques/cookies.md
> +Once the installation is complete, register the `@fastify-cookie` plugin:
```suggestion
Once the installation is complete, register the `@fastify/cookie` plugin:
```

2022-05-05 19:35 UTC, micalevisk commented on content/techniques/cookies.md
> +import fastifyCookie from '@fastify-cookie';
```suggestion
import fastifyCookie from '@fastify/cookie';
```

2022-05-05 19:51 UTC, micalevisk approved these changes

2022-05-24 19:01 UTC, Jared-Pro commented
This PR should be merged. I installed multiple deprecated fastify packages due to the docs being outdated.

2022-05-26 08:26 UTC, shunkica commented
Why is it taking so long for such a simple change? I just wasted an hour because the docs said to use `fastify-cookie` but that package produced errors for me.

2022-06-15 11:31 UTC, merged

2022-06-15 11:32 UTC, kamilmysliwiec commented
Accidentally merged this PR @Tony133. Can you recreate it?

2022-06-15 11:53 UTC, Tony133 commented
Yes sure, I'll recreate the PR 👍