Update task-scheduling.md
nestjs/docs.nestjs.com pull request #2315
Opened 2022-05-19 09:41 UTC by manoj-manoharan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2022-05-19 14:35 UTC, micalevisk commented on content/techniques/task-scheduling.md
> +Register the service in AppModule
```suggestion
Register the service in `AppModule`
```

2022-05-19 14:52 UTC, Tony133 requested changes
There is an extra space between the text and the code above, for the rest it's fine. 👍

2022-05-19 14:52 UTC, Tony133 commented on content/techniques/task-scheduling.md
> +
```suggestion
```

2022-05-20 12:03 UTC, kamilmysliwiec commented
This should be obvious to anyone who at least walked through the "Overview" category which is essential to understanding later chapters.

2022-05-20 12:03 UTC, closed without merging