docs(recipes): add recipe for automock library
nestjs/docs.nestjs.com pull request #2340
Opened 2022-06-05 14:45 UTC by omermorad

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Docs
- [ ] Other... Please describe:

**Issue Number: #2288** 

## Other information

2022-06-26 14:30 UTC, omermorad commented
@jmcdo29 @kamilmysliwiec I'm still working on this one, I have tons of work in my workplace, but I believe I will finish this one soon.
@kamilmysliwiec in the meanwhile, I would really appreciate your opinion in this thread https://github.com/nestjs/docs.nestjs.com/issues/2288 :) :)

2022-11-19 15:24 UTC, omermorad commented
@kamilmysliwiec, @jmcdo29 - I think everything is ready, I will appreciate your review :)

2022-12-27 01:11 UTC, jmcdo29 requested changes
Looking good. I noticed a few small changes to make. One question, what does the `.mock()` do? Maybe add that in with the `unit` and `unitRef` section as it all comes around `.compile()`?

2022-12-27 01:11 UTC, jmcdo29 commented on content/recipes/automock.md
> +class external providers, resulting in total isolation of the unit under test.
```suggestion
The dependency injection (DI) container is an essential component of the Nest module system.
This container is utilized both during testing, and the application execution.
Unit tests vary from other types of tests, such as integration tests, in that they must
fully override providers/services within the DI container. External class dependencies
(providers) of the so-called "unit", have to be totally isolated. That is, all dependencies
within the DI container should be replaced by mock objects.
As a result, loading the target module and replacing the providers inside it is a process
that loops back on itself. Automock tackles this issue by automatically mocking all the
class external providers, resulting in total isolation of the unit under test.
```

2022-12-27 01:11 UTC, jmcdo29 commented on content/recipes/automock.md
> +
```suggestion

> info **info** `automock` is a third party package and is not managed by the NestJS core team. Please, report any issues found with the library in the [appropriate repository](<add your repo here>)

```

2022-12-27 01:11 UTC, jmcdo29 commented on content/recipes/automock.md
> +```ts
```suggestion
#### Example

Consider the following cats service, which takes three constructor parameters:

```ts
```
added whitespace

2022-12-27 01:11 UTC, jmcdo29 commented on content/recipes/automock.md
> +Let's examine the following code:
```suggestion
#### About `unit` and `unitRef`

Let's examine the following code:
```

2022-12-30 05:35 UTC, omermorad commented on content/recipes/automock.md
> +
Added manually.

2022-12-30 16:33 UTC, jmcdo29 approved these changes

2023-01-31 21:07 UTC, Tony133 approved these changes

2023-02-03 14:00 UTC, kamilmysliwiec commented on content/recipes/automock.md
> +    this.logger.log('successfully fetched all cats');
```suggestion
    this.logger.log('Successfully fetched all cats');
```

2023-02-03 14:01 UTC, merged

2023-02-03 14:01 UTC, kamilmysliwiec commented
lgtm

2023-02-03 14:01 UTC, kamilmysliwiec commented
lgtm