docs (microservices): add documentation for KafkaContext.heartbeat usage
nestjs/docs.nestjs.com pull request #2409
Opened 2022-07-19 14:20 UTC by kosh-b

## Add documentation of KafkaContext.heartbeat usage, related to: https://github.com/nestjs/nest/pull/9954

- [x] The commit message follows our guidelines: https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Docs
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [9949](https://github.com/nestjs/nest/issues/9949) (of nestjs itself)

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-07-19 19:43 UTC, Tony133 approved these changes

2022-07-20 13:35 UTC, jmcdo29 requested changes
Slight suggestion to grammar. Otherwise looks good

2022-07-20 13:35 UTC, jmcdo29 commented on content/microservices/kafka.md
> +If your endpoint involves slow processing time for each message you should consider calling `heartbeat` callback, use `getHeartbeat()` method of `KafkaContext` which will send heartbeat to the broker
```suggestion
If your endpoint involves slow processing time for each message you should consider using the `heartbeat` callback. To do this, use the `getHeartbeat()` method of the `KafkaContext` which will send heartbeat to the broker, as follows:
```

2022-07-20 19:43 UTC, kosh-b commented
Committed the suggestion:)

2022-07-21 07:55 UTC, kamilmysliwiec commented on content/microservices/kafka.md
> +If your endpoint involves slow processing time for each message you should consider using the `heartbeat` callback. To do this, use the `getHeartbeat()` method of the `KafkaContext` which will send h
```suggestion
If your handler involves a slow processing time for each received message you should consider using the `heartbeat` callback. To retrieve the `heartbeat` function, use the `getHeartbeat()` method of the `KafkaContext`, as follows:
```

2022-07-21 07:55 UTC, kamilmysliwiec commented on content/microservices/kafka.md
> +  // Send heartbeat when it's possible, in order to not exceed the sessionTimeout
```suggestion
  // Send heartbeat to not exceed the sessionTimeout
```

2022-07-21 07:55 UTC, kamilmysliwiec commented on content/microservices/kafka.md
> +  // Do some slow processing:
```suggestion
  // Do some slow processing
```

2022-07-21 07:55 UTC, kamilmysliwiec commented on content/microservices/kafka.md
> +  // Do some slow processing again:
```suggestion
  // Do some slow processing again
```

2022-07-21 07:56 UTC, kamilmysliwiec commented on content/microservices/kafka.md
> +  const originalMessage = context.getMessage();
```suggestion
```

2022-07-21 07:56 UTC, merged

2022-07-21 07:56 UTC, kamilmysliwiec commented
lgtm