add matchRoles in guards.md
nestjs/docs.nestjs.com pull request #3000
Opened 2024-03-29 09:09 UTC by qd-xiaowang

I think it adds to the understanding

Because if you import directly, an error message will be displayed

error TS2304: Cannot find name 'matchRoles'.

2024-04-19 23:03 UTC, prateekkathal requested changes

2024-04-19 23:03 UTC, prateekkathal commented on content/guards.md
> +    private matchRoles(requiredRoles: string[], userRoles: string[]): boolean {
Doesn't look this code is formatted. Kindly fix the formatting and the logic as per my previous message.

2024-04-19 23:03 UTC, prateekkathal commented on content/guards.md
> +    return this.matchRoles(roles, user.roles);
Thanks for adding this. I don't see value in adding a private function here. Developers have there own logic to `matchRoles`.

I would rather just re-write this to:

```
return matchRoles(roles, user.roles); // Custom function to match roles
```

2024-04-19 23:51 UTC, qd-xiaowang commented
Thank you very much. I have learned a lot!

---Original---
From: "Prateek ***@***.***&gt;
Date: Sat, Apr 20, 2024 07:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nestjs/docs.nestjs.com] Update guards.md &amp;&amp; custom-decorators.md(PR #3000)




 
@prateekkathal requested changes on this pull request.
 
 
In content/custom-decorators.md:
 &gt; @@ -118,7 +118,7 @@ import { createParamDecorator, ExecutionContext } from ***@***.***/common';  export const User = createParamDecorator(    (data: string, ctx: ExecutionContext) =&gt; {      const request = ctx.switchToHttp().getRequest(); -    const user = request.user; +    const user = request.body;  
Why would we change this decorator? This is not a decorator that NestJS comes with out of the box. This is a custom decorator that people can define themselves. You are free to create a different decorator to support your use-case.
 
 
In content/guards.md:
 &gt;    } + +  private matchRoles(requiredRoles: string[], userRoles: string[]): boolean {   +    for (const role of requiredRoles) {   +      if (userRoles.includes(role)) {   +        return true;    
Looks incorrect. This would return true as soon as first role is found. Doesn't match all roles.
 
 
In content/guards.md:
 &gt; @@ -224,7 +233,16 @@ export class RolesGuard {      }      const request = context.switchToHttp().getRequest();      const user = request.user; -    return matchRoles(roles, user.roles); +    return this.matchRoles(roles, user.roles); +  } + +    private matchRoles(requiredRoles: string[], userRoles: string[]): boolean {    
Doesn't look this code is formatted. Kindly fix the formatting and the logic as per my previous message.
 
 
In content/guards.md:
 &gt; @@ -202,8 +202,17 @@ export class RolesGuard implements CanActivate {      }      const request = context.switchToHttp().getRequest();      const user = request.user; -    return matchRoles(roles, user.roles); +    return this.matchRoles(roles, user.roles);  
Thanks for adding this. I don't see value in adding a private function here. Developers have there own logic to matchRoles.
 
I would rather just re-write this to:
 return matchRoles(roles, user.roles); // Custom function to match roles  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-04-20 03:30 UTC, qd-xiaowang commented on content/guards.md
> +        return true;
Learn a lot，thanks!

2024-10-17 08:20 UTC, closed without merging